name: Latihan 1
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install update
        run: sudo apt update -y
      - name: Install nginx
        run: sudo apt install nginx -y
      - name: Tes landing page nginx
        run: sudo systemctl start nginx && curl localhost
